/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package lp.condominios.forms;

import java.math.BigDecimal;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import lp.condominios.enums.ApartamentoModelList;
import lp.condominios.models.*;
import lp.condominios.models.exceptions.NonexistentEntityException;

/**
 *
 * @author Pedro
 */
public class frameMovimentoForm extends javax.swing.JFrame {

    private int intID;
    private MovimentoJpaController controller;
    private Movimento movimento;
    
    private BigDecimal calcularValor(double d, int Mes, int Ano, Date data) { 
        if (data.getDate() <= 8 && (data.getMonth() + 1) > Mes && (1900 + data.getYear()) >= Ano) {
           d = d + (d * 0.02);
        } else {
            if ((data.getMonth() + 1) > Mes && (1900 + data.getYear()) >= Ano) {
                 d = d + (d * 0.05);
            }            
        }
        
        return new BigDecimal(d);       
    }
    
    /**
     * Creates new form frameMovimentoForm
     */
    public frameMovimentoForm() {
        initComponents();
    }

    public frameMovimentoForm(int ID) {
        this();
        
        this.intID = ID;
        
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm");
        
        Date d = new Date();
        txtMes.setText(new Integer(d.getMonth()).toString());
        txtAno.setText(new Integer((1900 + d.getYear())).toString());
        
        // Conectar o apartamento
        controller = new MovimentoJpaController(entityManager1.getEntityManagerFactory());
        
        cmbApartamento.setModel(new ApartamentoModelList(entityManager1.getEntityManagerFactory()));
        
        if (intID == 0) {
            this.setTitle("Adicionar Movimento");
            btnDelete.setVisible(false);
            
            txtValor.setText("0,00");
            txtData.setText(dateFormat.format(new Date()));
            
            movimento = new Movimento();
            
        } else {
            this.setTitle("Editar Movimento: "  + intID);
            
            // Ler os dados da base de dados
            movimento = controller.findMovimento(intID);
            
            txtID.setText(movimento.getId().toString());
            txtDescricao.setText(movimento.getDescricao().toString());
            cmbApartamento.setSelectedIndex(movimento.getIdapartamento());
            txtValor.setText(movimento.getValor().toString());
            txtData.setText(dateFormat.format(movimento.getData()));
            txtMes.setText(new Integer(movimento.getMes()).toString());
            txtAno.setText(new Integer(movimento.getAno()).toString());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entityManager1 = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("lp.condominiosPU").createEntityManager();
        btnDelete = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        btnOK = new javax.swing.JButton();
        lblID = new javax.swing.JLabel();
        lblDescricao = new javax.swing.JLabel();
        lblApartamento = new javax.swing.JLabel();
        lblValor = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtDescricao = new javax.swing.JTextField();
        cmbApartamento = new javax.swing.JComboBox();
        txtValor = new javax.swing.JTextField();
        txtData = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtMes = new javax.swing.JTextField();
        txtAno = new javax.swing.JTextField();

        btnDelete.setBackground(new java.awt.Color(255, 0, 0));
        btnDelete.setText("Apagar");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnClose.setText("Sair");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        lblID.setText("ID");

        lblDescricao.setText("Descrição");

        lblApartamento.setText("Apartamento");

        lblValor.setText("Valor");

        lblData.setText("Data do Pagamento");

        txtID.setText("0");
        txtID.setEnabled(false);

        cmbApartamento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtData.setEnabled(false);

        jLabel1.setText("Mês / Ano");

        txtAno.setText("2013");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 203, Short.MAX_VALUE)
                        .addComponent(btnOK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClose)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblID)
                            .addComponent(lblDescricao)
                            .addComponent(lblApartamento))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDescricao)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbApartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblValor)
                            .addComponent(lblData)
                            .addComponent(jLabel1))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtMes, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtValor)
                            .addComponent(txtData))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblID)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDescricao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApartamento)
                    .addComponent(cmbApartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOK)
                    .addComponent(btnClose)
                    .addComponent(btnDelete))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try {
            controller.destroy(intID);
            btnCloseActionPerformed(evt);
            
        } catch (NonexistentEntityException ex) {
            Logger.getLogger(frameApartamentoForm.class.getName()).log(Level.SEVERE, null, ex);
            
            JOptionPane.showMessageDialog(null, "Erro ao apagar o registo.", "Apagar", JOptionPane.ERROR_MESSAGE);
        } 
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        if (movimento == null) {
           JOptionPane.showMessageDialog(null, "Ocorreu um erro o movimento não foi encontrado.", "Erro", JOptionPane.ERROR_MESSAGE);
       }
       
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm");  
        
        
        BigDecimal d = new BigDecimal(txtValor.getText());
        try {
            d = calcularValor(d.doubleValue(), 
                    Integer.parseInt(txtMes.getText()), 
                    Integer.parseInt(txtAno.getText()), dateFormat.parse(txtData.getText()));
            
        } catch (ParseException ex) {
            Logger.getLogger(frameMovimentoForm.class.getName()).log(Level.SEVERE, null, ex);
            
        }
               
        try {
            movimento.setDescricao(txtDescricao.getText());
            movimento.setIdapartamento(((Apartamento)cmbApartamento.getSelectedItem()).getId());
            movimento.setValor(d);
            movimento.setData(dateFormat.parse(txtData.getText()));
            movimento.setMes(Integer.parseInt(txtMes.getText()));
            movimento.setAno(Integer.parseInt(txtAno.getText()));
            
            if (intID == 0) {
                controller.create(movimento);                           
            } else {
                controller.edit(movimento);
            }
            
            btnCloseActionPerformed(evt);            
       
        } catch (Exception ex) {
            Logger.getLogger(frameProprietarioForm.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Ocorreu um erro gravar o movimento.", "Erro", JOptionPane.ERROR_MESSAGE);
        }  
    }//GEN-LAST:event_btnOKActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnOK;
    private javax.swing.JComboBox cmbApartamento;
    private javax.persistence.EntityManager entityManager1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblApartamento;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblValor;
    private javax.swing.JTextField txtAno;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtMes;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
